apiVersion: v1
kind: Secret
metadata:
  name: dartmaster-secret
  namespace: dartmaster
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_USER: "dartmaster"
  MYSQL_PASSWORD: "dartmaster"
  DATABASE_USER: "dartmaster"
  DATABASE_PASSWORD: "dartmaster"
